export const cholulaMeta = {
  title: "Cholula Hot Sauce",
  description:
    "Three years as lead designer on Uncap Real Flavor — national TV, chalk-on-slate print, and a visual system that scaled across every channel.",
} as const;

export const cholulaHero = {
  kicker: "Case study · Cholula · Spitball Advertising",
  lockup: "Uncap Real Flavor",
  title: "Cholula Hot Sauce",
  deck: "Three years as lead designer on Uncap Real Flavor — national TV, chalk-on-slate print, and a visual system that scaled across every channel.",
  tags: ["Campaigns", "Art Direction", "Print", "Video"],
  intro:
    "At Spitball Advertising, I grew into the lead designer role on the agency's biggest accounts. Cholula was the one I returned to for three consecutive years. I developed the chalk-on-slate visual system, drew every flavor illustration from scratch, and art-directed the national TV spot, print, social, broadcast, and in-store, all anchored by the same handmade aesthetic.",
} as const;

export const cholulaPillars = [
  {
    name: "Authenticity",
    body: "Compete with bigger hot sauce brands by looking handmade and warm, not manufactured. Craft is the advantage when the budget is not.",
  },
  {
    name: "Craft",
    body: "Chalk on slate. Hand-rendered type. Textured surfaces. Real food, shot like it was made in a kitchen, not a catalog.",
  },
  {
    name: "Range",
    body: "The same feeling had to travel from an in-store display to a 30-second national spot without going thin or going loud.",
  },
] as const;

export const cholulaScope = [
  {
    title: "Print system",
    body: "The chalk-on-slate visual language: hand-rendered typography, textured surfaces, and artisan food photography that could hold a wall or a magazine spread.",
  },
  {
    title: "Illustration library",
    body: "Every flavor illustration digitally drawn from scratch — each ingredient, pairing, and SKU — then managed as an agency-wide asset library for two years.",
  },
  {
    title: "Digital & social",
    body: "MLB Gameday tie-ins, drag-and-drop social executions, OOH, and platform-native formats, all inherited from the same slate foundation.",
  },
  {
    title: "National TV",
    body: "Art direction on the broadcast commercial: camera, surface textures, type integration, and color grading, then cut down for social and digital.",
  },
] as const;

export const cholulaOutcomes = [
  {
    stat: "3 yrs",
    label: "Lead designer",
    body: "Returned to the same platform for three consecutive years — rare in agency work, and the reason the system had to grow instead of repeat.",
  },
  {
    stat: "12%",
    label: "Brand awareness",
    body: "Estimated lift from the Uncap Real Flavor campaign across print, social, broadcast, and in-store.",
  },
  {
    stat: "$14M",
    label: "Earned media",
    body: "Estimated earned media generated by the national TV spot and the system that ran alongside it.",
  },
] as const;

export const cholulaChannels = [
  "Print",
  "Packaging",
  "In-store",
  "OOH",
  "Social",
  "Digital",
  "Broadcast",
  "Illustration",
] as const;

export const cholulaVideos = [
  {
    title: "Cholula Uncap Real Flavor, Commercial 1",
    embed: "https://www.youtube-nocookie.com/embed/Y0eQLxg9H_Q",
  },
  {
    title: "Cholula Uncap Real Flavor, Commercial 2",
    embed: "https://www.youtube-nocookie.com/embed/jgV2B6mYnsE",
  },
] as const;

export const cholulaCredits = [
  {
    heading: "Role",
    items: [
      "Lead designer, Spitball Advertising",
      "Three consecutive years on Cholula",
      "Art direction across print, social, broadcast, and in-store",
    ],
  },
  {
    heading: "What I made",
    items: [
      "Chalk-on-slate visual system",
      "Every flavor illustration, drawn from scratch",
      "Agency illustration library, managed two years",
      "National TV commercial art direction",
    ],
  },
  {
    heading: "System",
    items: [
      "Hand-rendered type on slate",
      "Artisan food photography",
      "Wood, chalk, and Cholula red",
      "One handmade aesthetic, every channel",
    ],
  },
] as const;
